### ISSUE TITLE
Bower install fails

### ISSUE THREAD

**Issue by creatifyme** [arnaudbreton/angular-smoothscroll#1]
Running the command on the bower install angular-smoothscroll I get the following error:

bower cloning git://github.com:arnaudbreton/angular-smoothscroll.git
bower caching git://github.com:arnaudbreton/angular-smoothscroll.git
bower error status code of git: 128

There were errors, here's a summary of them:
- angular-smoothscroll status code of git: 128
  fatal: Unable to look up github.com (port arnaudbreton) (The specified class was
  not found. )

Environment:
Windows 8 - 64bit
Bower 0.9.2

**Comment by arnaudbreton** [comment]
Hi, 

The bower registration was made with a wrong URL. I have asked them to remove it and I'm waiting now.
While waiting, you can install it with the full repo URL: `bower install git://github.com/arnaudbreton/angular-smoothscroll.git``

Let me know if it works.

**Comment by creatifyme** [comment]
That did work. Thank you.

**Comment by arnaudbreton** [comment]
Great! Thanks for keeping me updated. Enjoy!

**Comment by arnaudbreton** [comment]
URL has been updated, this module can now be installed through bower now via `bower install angular-smoothscroll`

**Comment by sunz7** [comment]
Great answer!!
