### ISSUE TITLE
semver tags + bower.json and register with bower

### ISSUE THREAD

**Issue by oGLOWo** [arnaudbreton/angular-smoothscroll#14]
Hi. Could you please create a semver tag along with the bower.json so that you can register the package with bower. This should allow the entire community to easily set their bower.json dependency to "angular-smoothscroll": "1.0.0" --> or whatever version you deem appropriate.

**Comment by arnaudbreton** [comment]
Hi @oGLOWo,

The package is already registered with Bower: http://bower.io/search/?q=angular-smoothscroll
I've just released the 1.1.0, you should be able to use it as a dependency now. Let me know if it works for you.

**Comment by oGLOWo** [comment]
Hey I just checked it out and all is good except some dependency version conflicts. I sent a pull request to see what you think. In any case, thank you for responding quickly!
