### ISSUE TITLE
bower.json references non-existent path for "main"

### ISSUE THREAD

**Issue by programbo** [arnaudbreton/angular-smoothscroll#19]
References `"main": "dist/scripts/2d8e100/scripts.js",`

...but the target file is `dist/scripts/c8742280.scripts.js`

Could be a broken build script, or just a literal string that hasn't been updated.

**Comment by lonormaly** [comment]
+1!

**Comment by arnaudbreton** [comment]
Sorry for the delay, I'll try to give a look ASAP.

**Comment by arnaudbreton** [comment]
Fixed by 6973190ee328a0ef517fd1c005c68a9625ea10a4
