### ISSUE TITLE
Set fallback offset to 0

### ISSUE THREAD

**Issue by larrybotha** [arnaudbreton/angular-smoothscroll#21]
A well styled document should handle where the page scrolls to by default - a default offset of 100px is essentially magic, as the div / element it scrolls to may require a more specific offset - perhaps 1em, etc. The odds of this having to be overridden  on a frequent basis are far greater than if it is set to a safe and unassuming 0, allowing CSS to account for spacing within elements or containers.

i.e. with offset=100

``` html
<div id="some-div" style="background-color: grey; padding-top: 2rem;">
  content
</div>
```

will show a nasty 100px band of colour above this div from the previous content. 

Setting offset=0 by default will ensure that the styling can handle this instead. Not setting padding would sit the content right against the top of the div - a design faux pas - so the CSS / design should naturally handle the case for offset=0.

For special cases, the scroll element may set a custom offset, as per usual.

**Comment by arnaudbreton** [comment]
I agree with you on the default value. Meanwhile, it is something that you can pass via the attribute `offset` to configure it. Have you noticed this ? Thanks for your contribution, just merged your PR

**Comment by larrybotha** [comment]
Ye, I've had to use the offset on a site in multiple locations, which is why I came here with the recommendation :)

Thanks for the merge!
