### ISSUE TITLE
example

### ISSUE THREAD

**Issue by yoshuawuyts** [arnaudbreton/angular-smoothscroll#6]
Hey, could you link an example of your working code? It would be nice for future visitors to see how it functions out in the wild. Thanks!

**Comment by arnaudbreton** [comment]
Hey!

You can find a working example here: http://plnkr.co/edit/rD0Zgi6rg3Spc2XeVrZf?p=preview

Please let me know if it work for you as well!
Arnaud.

**Comment by yoshuawuyts** [comment]
Yes, thanks a many! Maybe you could add this to `readme.md` for others to see. But I was wondering, is it possible to slow the effect down (ease-in, ease-out) for an extra smooth effect?

**Comment by arnaudbreton** [comment]
Yes you're right! I've just did it.

Regarding the speed, as described in the README, it is available only in
the jQuery version at the moment, for some technical reasons I've not
figured out yet.
Feel free to contribute to the Vanilla JS version to improve it. Would be
really appreciated!

You can declare the speed (default is 500):<a smooth-scroll-jquery

> target="target" speed="1000">Scroll to Target</a>

Please let me know if it works for you.

Best.

On Sun, Sep 8, 2013 at 1:00 PM, Yoshua notifications@github.com wrote:

> Yes, thanks a many! Maybe you could add this to `readme.md for others to
> see. But I was wondering, is it possible to slow the effect down (ease-in,
> ease-out) for an extra smooth effect?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arnaudbreton/angular-smoothscroll/issues/6#issuecomment-24018860
> .

## 

Arnaud BRETON
Co-founder and CTO @ VideoNot.es / UniShared http://unishared.com/
Phone number: +1 (650) 308-4410 (Google voice)
LinkedIn http://www.linkedin.com/pub/arnaud-breton/30/60a/b78/
Twitter https://twitter.com/arnaud_breton
Facebook https://www.facebook.com/arnaud.breton

**Comment by yoshuawuyts** [comment]
@arnaudbreton Thanks man, I'll definitely look under the hood to see if I can make it work! Thanks!
