### ISSUE TITLE
Installation with Bower installs extraneous packages

### ISSUE THREAD

**Issue by axelav** [arnaudbreton/angular-smoothscroll#9]
Why does the installation using Bower also install these packages?
- angular.js
- es5-shim
- jquery
- json3

This overwrites the version of angular I'm already using in my project. I would assume that most users of this already have angular installed & probably jquery too...

**Comment by konsumer** [comment]
It's good for this project to track it's dependencies. In your project's bower.json,  you can put this:

```
"resolutions": {
  "angular": "~1.2.13"
}
```

replace `~1.2.13` with whatever version you are using.
